name: springboot-jar
on: workflow_dispatch
jobs:
  sb-package:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Run the Maven verify phase
        run: mvn clean package -DskipTests=true
#      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: app
          path: target/Hello.jar
        
        
